language: objective-c
xcode_workspace: LinkedNote.xcworkspace
xcode_scheme: LinkedNote
xcode_sdk: iphonesimulator11.2
osx_image: xcode9.2

before_install:
    - gem install xcpretty
    - pod repo update
    - gem install cocoapods-keys
    - pod keys set PocketAPIConsumerKey "-"
    - pod keys set PocketAppID "-"
    - echo "POCKET_APP_ID=pocketapp" > .env

script:
    - xcodebuild -workspace LinkedNote.xcworkspace -scheme LinkedNote -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.2,name=iPhone 7' -configuration Debug test | xcpretty && exit ${PIPESTATUS[0]}
