xcode_sdk: iphonesimulator
language: objective-c
matrix:
    include:
        - osx_image: xcode8.3
script:
    - xcodebuild -scheme ios-travis -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.1,name=iPhone 7' -configuration Debug test | xcpretty -c
