xcode_sdk: iphonesimulator
language: objective-c
matrix:
    include:
        - osx_image: xcode8.3

before_install:
    - gem install cocoapods-keys
    - pod keys set PocketAPIConsumerKey "-"
    - exec pod keys set PocketAppID "-"
    - echo "POCKET_APP_ID=pocketapp" > .env

script:
    - xcodebuild -scheme ios-travis -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.1,name=iPhone 7' -configuration Debug test | xcpretty -c
