# coding: utf-8
# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'LinkedNote' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'PocketAPI', :git => 'https://github.com/tasuwo/Pocket-ObjC-SDK'
  pod 'SwiftyJSON', '4.0.0'
  pod 'RealmSwift', '3.1.1'
  pod 'DynamicColor', '4.0.2'
  pod 'SwiftFormat/CLI', '~> 0.33.4'

  plugin 'cocoapods-keys', {
    :project => "LinkedNote",
    :keys => [
      "PocketAPIConsumerKey",
      "PocketAppID"
    ]
  }

  # Pods for LinkedNote

  target 'LinkedNoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LinkedNoteUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do | installer |
  # Move acknowledgements generated by cocoapods to app resources
  require 'fileutils'
  pod_plist = 'Pods/Target Support Files/Pods-LinkedNote/Pods-LinkedNote-acknowledgements.plist'
  app_plist = 'LinkedNote/resources/Settings.bundle/Acknowledgements.plist'
  FileUtils.cp_r(pod_plist, app_plist, :remove_destination => true)

  # Add licenses of libraries which not managed in cocoapods to plist
  require 'yaml'
  tmp = Xcodeproj::Plist.read_from_path(app_plist)
  last_node = tmp["PreferenceSpecifiers"].pop()
  YAML.load_file("./LinkedNote/resources/manual_installed_libraries_acknowledgements.yml").each{ |i|
    tmp["PreferenceSpecifiers"].push(i)
  }
  tmp["PreferenceSpecifiers"].push(last_node)
  Xcodeproj::Plist.write_to_path(tmp, app_plist)
end
